export const SEASONS = ['Spring', 'Summer', 'Autumn', 'Winter'];
export const ACTION_LIMIT = 2;
export const LOG_LIMIT = 10;
export const TICKS_PER_SEASON = 6;
export const SPEED_OPTIONS = [
  { label: '1x', value: 1, tickMs: 1000 },
  { label: '2x', value: 2, tickMs: 550 },
  { label: '4x', value: 4, tickMs: 280 },
];

export const DISTRICT_LAYOUT = [
  { key: 'civic', label: 'Civic Core', type: 'civic', x: 0.355, y: 0.145, w: 0.29, h: 0.22 },
  { key: 'north', label: 'North Steps', type: 'residential', x: 0.645, y: 0.09, w: 0.225, h: 0.25 },
  { key: 'harbor', label: 'Rivergate', type: 'utility', x: 0.105, y: 0.16, w: 0.21, h: 0.27 },
  { key: 'market', label: 'Market Spine', type: 'commercial', x: 0.34, y: 0.395, w: 0.325, h: 0.2 },
  { key: 'park', label: 'Green Loop', type: 'park', x: 0.105, y: 0.505, w: 0.225, h: 0.25 },
  { key: 'industry', label: 'Ironworks', type: 'industrial', x: 0.675, y: 0.445, w: 0.2, h: 0.245 },
  { key: 'south', label: 'South Reach', type: 'mixed', x: 0.355, y: 0.66, w: 0.295, h: 0.19 },
];

export const WORLD_LAYOUT = {
  cols: 26,
  rows: 22,
  waterCols: 4,
  mainAvenues: {
    rows: [12],
    cols: [13],
  },
  safeArea: {
    left: 56,
    right: 360,
    top: 92,
    bottom: 172,
  },
  districts: {
    harbor: { x: 5, y: 8, w: 4, h: 3, frontage: 'east' },
    civic: { x: 10, y: 8, w: 4, h: 3, frontage: 'south' },
    north: { x: 14, y: 5, w: 4, h: 3, frontage: 'south' },
    market: { x: 15, y: 10, w: 4, h: 3, frontage: 'west' },
    park: { x: 8, y: 13, w: 4, h: 3, frontage: 'north' },
    industry: { x: 17, y: 13, w: 4, h: 3, frontage: 'north' },
    south: { x: 11, y: 16, w: 5, h: 3, frontage: 'north' },
  },
};

export const DISTRICT_MODELS = {
  civic: {
    housing: 8,
    jobs: 24,
    serviceSupply: 30,
    transitSupply: 22,
    revenueBase: 7,
    upkeep: 8,
    appeal: 0.62,
    stability: 18,
  },
  residential: {
    housing: 74,
    jobs: 12,
    serviceNeed: 18,
    transitDemand: 14,
    upkeep: 4,
    appeal: 0.72,
    stability: 8,
  },
  utility: {
    jobs: 18,
    powerSupply: 36,
    waterSupply: 38,
    serviceSupply: 4,
    transitSupply: 12,
    upkeep: 7,
    appeal: 0.38,
    stability: 10,
  },
  commercial: {
    housing: 8,
    jobs: 40,
    revenueBase: 20,
    transitSupply: 16,
    serviceNeed: 10,
    upkeep: 6,
    appeal: 0.56,
    stability: 4,
  },
  industrial: {
    jobs: 46,
    production: 32,
    revenueBase: 15,
    powerDemand: 20,
    waterDemand: 12,
    transitDemand: 22,
    upkeep: 9,
    appeal: 0.28,
    stability: -8,
  },
  park: {
    housing: 4,
    jobs: 10,
    food: 28,
    waterSupply: 6,
    serviceSupply: 20,
    upkeep: 3,
    appeal: 0.78,
    stability: 12,
  },
  mixed: {
    housing: 42,
    jobs: 28,
    revenueBase: 12,
    transitSupply: 12,
    transitDemand: 14,
    serviceNeed: 14,
    upkeep: 5,
    appeal: 0.65,
    stability: 6,
  },
};

export const ASSET_DEFINITIONS = [
  {
    key: 'civic-hall',
    districtKey: 'civic',
    label: 'Council Hall',
    maxLevel: 4,
    effects: { serviceSupply: 12, stability: 8, transitSupply: 6, upkeep: 2 },
  },
  {
    key: 'north-terraces',
    districtKey: 'north',
    label: 'Terrace Housing',
    maxLevel: 4,
    effects: { housing: 22, appeal: 0.08, serviceNeed: 4, transitDemand: 4, upkeep: 1 },
  },
  {
    key: 'harbor-grid',
    districtKey: 'harbor',
    label: 'Tidal Grid',
    maxLevel: 4,
    effects: { powerSupply: 30, waterSupply: 18, jobs: 4, upkeep: 3 },
  },
  {
    key: 'market-exchange',
    districtKey: 'market',
    label: 'Trade Exchange',
    maxLevel: 4,
    effects: { jobs: 12, revenueBase: 14, transitSupply: 8, upkeep: 2 },
  },
  {
    key: 'park-greenhouses',
    districtKey: 'park',
    label: 'Greenhouses',
    maxLevel: 4,
    effects: { food: 18, serviceSupply: 6, waterSupply: 4, appeal: 0.05, upkeep: 1 },
  },
  {
    key: 'industry-foundry',
    districtKey: 'industry',
    label: 'Foundry Line',
    maxLevel: 4,
    effects: { jobs: 16, production: 18, revenueBase: 10, powerDemand: 12, pollution: 12, upkeep: 3 },
  },
  {
    key: 'south-crossings',
    districtKey: 'south',
    label: 'Mixed-Use Blocks',
    maxLevel: 4,
    effects: { housing: 18, jobs: 10, transitSupply: 10, appeal: 0.05, upkeep: 2 },
  },
];

export const ACTIONS = [
  {
    key: 'housing',
    label: 'Expand Housing',
    note: 'Upgrades the district under the strongest housing pressure.',
  },
  {
    key: 'grid',
    label: 'Harden Grid',
    note: 'Boosts utility output at Rivergate to relieve power and water strain.',
  },
  {
    key: 'industry',
    label: 'Back Industry',
    note: 'Raises production and jobs, but increases load and unrest risk.',
  },
  {
    key: 'services',
    label: 'Fund Services',
    note: 'Strengthens civic services to calm unrest and support growth.',
  },
];

export const OPEN_ASSET_FILES = {
  city: 'assets/open/pixel-city/pixel city_0.png',
  municipal: 'assets/open/municipal-buildings/municipal buildings_0.png',
  brick: 'assets/open/brick-apartments/brick_buildings.PNG',
  brickLarge: 'assets/open/brick-apartments/brick_lg.PNG',
  roadsA: 'assets/open/streets-and-avenues/spr_roads_1_strip15_1.png',
  roadsB: 'assets/open/streets-and-avenues/spr_road_2_strip29_2.png',
};

export const SPRITE_CATALOG = {
  'municipal-west-hall': {
    sheet: 'municipal',
    sourceRectPx: [2, 24, 70, 49],
    districtTypes: ['civic'],
    baseScale: 0.9,
    visualWeight: 1.08,
    sizeClass: 'hall',
  },
  'municipal-east-hall': {
    sheet: 'municipal',
    sourceRectPx: [166, 19, 70, 54],
    districtTypes: ['civic', 'utility'],
    baseScale: 0.88,
    visualWeight: 1.06,
    sizeClass: 'hall',
  },
  'municipal-clinic': {
    sheet: 'municipal',
    sourceRectPx: [85, 26, 66, 46],
    districtTypes: ['civic', 'utility'],
    baseScale: 0.82,
    visualWeight: 1.02,
    sizeClass: 'mid',
  },
  'municipal-service-east': {
    sheet: 'municipal',
    sourceRectPx: [244, 25, 70, 48],
    districtTypes: ['utility'],
    baseScale: 0.84,
    visualWeight: 1.02,
    sizeClass: 'mid',
  },
  'municipal-kiosk-a': {
    sheet: 'municipal',
    sourceRectPx: [23, 88, 34, 29],
    districtTypes: ['civic', 'park'],
    baseScale: 0.92,
    visualWeight: 0.94,
    sizeClass: 'small',
  },
  'municipal-kiosk-b': {
    sheet: 'municipal',
    sourceRectPx: [100, 88, 34, 29],
    districtTypes: ['civic', 'park'],
    baseScale: 0.92,
    visualWeight: 0.94,
    sizeClass: 'small',
  },
  'municipal-kiosk-c': {
    sheet: 'municipal',
    sourceRectPx: [185, 89, 34, 29],
    districtTypes: ['park', 'utility'],
    baseScale: 0.92,
    visualWeight: 0.94,
    sizeClass: 'small',
  },
  'municipal-kiosk-d': {
    sheet: 'municipal',
    sourceRectPx: [262, 89, 34, 29],
    districtTypes: ['park', 'utility'],
    baseScale: 0.92,
    visualWeight: 0.94,
    sizeClass: 'small',
  },
  'municipal-garden-west': {
    sheet: 'municipal',
    sourceRectPx: [80, 137, 34, 29],
    districtTypes: ['park'],
    baseScale: 0.9,
    visualWeight: 0.96,
    sizeClass: 'small',
  },
  'municipal-garden-east': {
    sheet: 'municipal',
    sourceRectPx: [200, 188, 34, 27],
    districtTypes: ['park', 'civic'],
    baseScale: 0.9,
    visualWeight: 0.94,
    sizeClass: 'small',
  },
  'city-tower-west': {
    sheet: 'city',
    sourceRectPx: [127, 224, 34, 66],
    districtTypes: ['commercial', 'mixed', 'industrial'],
    baseScale: 0.98,
    visualWeight: 0.8,
    sizeClass: 'tower',
  },
  'city-tower-east': {
    sheet: 'city',
    sourceRectPx: [177, 225, 34, 65],
    districtTypes: ['commercial', 'mixed'],
    baseScale: 0.98,
    visualWeight: 0.8,
    sizeClass: 'tower',
  },
  'city-mid-block': {
    sheet: 'city',
    sourceRectPx: [57, 228, 52, 63],
    districtTypes: ['commercial', 'mixed'],
    baseScale: 0.92,
    visualWeight: 0.96,
    sizeClass: 'mid',
  },
  'city-low-block': {
    sheet: 'city',
    sourceRectPx: [242, 270, 52, 32],
    districtTypes: ['commercial', 'utility'],
    baseScale: 0.94,
    visualWeight: 1.06,
    sizeClass: 'low',
  },
  'city-mid-slim': {
    sheet: 'city',
    sourceRectPx: [177, 301, 34, 60],
    districtTypes: ['commercial', 'mixed'],
    baseScale: 0.94,
    visualWeight: 0.82,
    sizeClass: 'tower',
  },
  'city-mid-office': {
    sheet: 'city',
    sourceRectPx: [59, 309, 52, 48],
    districtTypes: ['commercial', 'mixed'],
    baseScale: 0.9,
    visualWeight: 0.98,
    sizeClass: 'mid',
  },
  'city-strip-industrial': {
    sheet: 'city',
    sourceRectPx: [220, 329, 70, 39],
    districtTypes: ['industrial', 'utility'],
    baseScale: 0.94,
    visualWeight: 1.06,
    sizeClass: 'low',
  },
  'city-mid-warehouse': {
    sheet: 'city',
    sourceRectPx: [10, 369, 52, 56],
    districtTypes: ['industrial', 'utility'],
    baseScale: 0.9,
    visualWeight: 0.98,
    sizeClass: 'mid',
  },
  'city-slim-warehouse': {
    sheet: 'city',
    sourceRectPx: [128, 367, 34, 58],
    districtTypes: ['industrial', 'mixed'],
    baseScale: 0.92,
    visualWeight: 0.82,
    sizeClass: 'tower',
  },
  'brick-office': {
    sheet: 'brick',
    sourceRectPx: [244, 115, 66, 37],
    districtTypes: ['commercial', 'mixed'],
    baseScale: 0.9,
    visualWeight: 1.02,
    sizeClass: 'low',
  },
  'brick-mid-west': {
    sheet: 'brick',
    sourceRectPx: [19, 250, 66, 82],
    districtTypes: ['residential', 'mixed'],
    baseScale: 0.76,
    visualWeight: 0.98,
    sizeClass: 'tower',
  },
  'brick-mid-east': {
    sheet: 'brick',
    sourceRectPx: [231, 249, 66, 79],
    districtTypes: ['residential', 'mixed'],
    baseScale: 0.76,
    visualWeight: 0.98,
    sizeClass: 'tower',
  },
  'brick-mid-center': {
    sheet: 'brick',
    sourceRectPx: [172, 250, 38, 66],
    districtTypes: ['residential', 'mixed'],
    baseScale: 0.84,
    visualWeight: 0.84,
    sizeClass: 'tower',
  },
  'brick-plant-west': {
    sheet: 'brick',
    sourceRectPx: [257, 347, 50, 53],
    districtTypes: ['industrial'],
    baseScale: 0.88,
    visualWeight: 0.92,
    sizeClass: 'mid',
  },
  'brick-plant-east': {
    sheet: 'brick',
    sourceRectPx: [197, 350, 50, 49],
    districtTypes: ['industrial'],
    baseScale: 0.88,
    visualWeight: 0.92,
    sizeClass: 'mid',
  },
  'brick-mixed-corner': {
    sheet: 'brick',
    sourceRectPx: [136, 354, 50, 45],
    districtTypes: ['mixed'],
    baseScale: 0.88,
    visualWeight: 0.92,
    sizeClass: 'mid',
  },
  'brick-south-block': {
    sheet: 'brick',
    sourceRectPx: [78, 358, 50, 41],
    districtTypes: ['mixed', 'park'],
    baseScale: 0.88,
    visualWeight: 0.92,
    sizeClass: 'mid',
  },
  'brick-loft': {
    sheet: 'brick',
    sourceRectPx: [170, 74, 50, 47],
    districtTypes: ['commercial', 'mixed'],
    baseScale: 0.9,
    visualWeight: 0.92,
    sizeClass: 'mid',
  },
  'bricklarge-tower-west': {
    sheet: 'brickLarge',
    sourceRectPx: [32, 499, 132, 164],
    districtTypes: ['residential'],
    baseScale: 0.52,
    visualWeight: 1.0,
    sizeClass: 'tower',
  },
  'bricklarge-tower-east': {
    sheet: 'brickLarge',
    sourceRectPx: [456, 497, 132, 158],
    districtTypes: ['residential'],
    baseScale: 0.52,
    visualWeight: 1.0,
    sizeClass: 'tower',
  },
  'bricklarge-mid-plaza': {
    sheet: 'brickLarge',
    sourceRectPx: [142, 317, 132, 92],
    districtTypes: ['mixed', 'commercial'],
    baseScale: 0.58,
    visualWeight: 1.02,
    sizeClass: 'mid',
  },
  'bricklarge-factory': {
    sheet: 'brickLarge',
    sourceRectPx: [334, 331, 100, 78],
    districtTypes: ['industrial'],
    baseScale: 0.64,
    visualWeight: 1.04,
    sizeClass: 'mid',
  },
};

export const DISTRICT_COMPOSITIONS = {
  civic: [
    { spriteId: 'municipal-west-hall' },
    { spriteId: 'municipal-clinic' },
    { spriteId: 'municipal-east-hall' },
    { spriteId: 'municipal-kiosk-a' },
    { spriteId: 'municipal-kiosk-b' },
  ],
  residential: [
    { spriteId: 'bricklarge-tower-west' },
    { spriteId: 'bricklarge-tower-east' },
    { spriteId: 'brick-mid-west' },
    { spriteId: 'brick-mid-center' },
    { spriteId: 'brick-mid-east' },
  ],
  utility: [
    { spriteId: 'municipal-clinic' },
    { spriteId: 'municipal-service-east' },
    { spriteId: 'city-strip-industrial' },
    { spriteId: 'municipal-kiosk-d' },
  ],
  commercial: [
    { spriteId: 'city-tower-west' },
    { spriteId: 'city-mid-block' },
    { spriteId: 'city-tower-east' },
    { spriteId: 'city-low-block' },
    { spriteId: 'brick-office' },
  ],
  industrial: [
    { spriteId: 'city-strip-industrial' },
    { spriteId: 'bricklarge-factory' },
    { spriteId: 'brick-plant-west' },
    { spriteId: 'brick-plant-east' },
  ],
  park: [
    { spriteId: 'municipal-kiosk-a' },
    { spriteId: 'municipal-kiosk-c' },
    { spriteId: 'municipal-garden-west' },
  ],
  mixed: [
    { spriteId: 'city-mid-office' },
    { spriteId: 'bricklarge-mid-plaza' },
    { spriteId: 'brick-mixed-corner' },
    { spriteId: 'city-slim-warehouse' },
  ],
};

export const ASSET_ICON_SPRITES = {
  'civic-hall': { sheet: 'municipal', region: [0.06, 0.06, 0.34, 0.52] },
  'north-terraces': { sheet: 'brick', region: [0.5, 0.08, 0.34, 0.64] },
  'harbor-grid': { sheet: 'roadsB', region: [0.4, 0.5, 0.2, 0.2] },
  'market-exchange': { sheet: 'city', region: [0.5, 0.06, 0.24, 0.22] },
  'park-greenhouses': { sheet: 'municipal', region: [0.36, 0.1, 0.18, 0.22] },
  'industry-foundry': { sheet: 'city', region: [0.52, 0.52, 0.26, 0.28] },
  'south-crossings': { sheet: 'brickLarge', region: [0.06, 0.1, 0.28, 0.68] },
};
